apiVersion: apps/v1
kind: Deployment
metadata:
  name: livraison-back-pipeline:1.0.0-25
spec:
  replicas: 2
  selector:
    matchLabels:
      app: livraison-back
  template:
    metadata:
      labels:
        app: livraison-back
    spec:
      containers:
        - name: livraison-back
          image: dali05/livraison-back-pipeline:1.0.0-25
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
