apiVersion: v1
kind: Service
metadata:
  name: livraison-back-service
  labels:
    app: livraison-back
spec:
  selector:
    app: livraison-back

  ports:
    - port: 8443
      targetPort: 8443

  type: LoadBalancer
