apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 5050
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: test@gmail.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "1234"  # Ajout des guillemets autour de la valeur
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: LoadBalancer
